install.log("FSR Bridge Lua 商城安装器已开始执行")

local fsr4_update = "auto"
local fsr4_upscaler_index = "auto"
local fsr4_force_int8 = "auto"
local fsr4_mode = "auto"
local gpu_name = "Unknown"
local gpu_vendor = "Unknown"

local amd_fp8_names = {
    ["AMD Radeon RX 9060"] = true,
    ["AMD Radeon RX 9060 GRE"] = true,
    ["AMD Radeon RX 9060 XT"] = true,
    ["AMD Radeon RX 9060 XT 16GB"] = true,
    ["AMD Radeon RX 9060 XT 8GB"] = true,
    ["AMD Radeon RX 9060 XTX"] = true,
    ["AMD Radeon RX 9060M"] = true,
    ["AMD Radeon RX 9070"] = true,
    ["AMD Radeon RX 9070 GRE"] = true,
    ["AMD Radeon RX 9070 XT"] = true,
    ["AMD Radeon RX 9070 XT 16GB"] = true,
    ["AMD Radeon RX 9070 XT 8GB"] = true,
    ["AMD Radeon RX 9070 XTX"] = true,
    ["AMD Radeon RX 9070M"] = true,
    ["AMD Radeon(TM) RX 9060"] = true,
    ["AMD Radeon(TM) RX 9060 GRE"] = true,
    ["AMD Radeon(TM) RX 9060 XT"] = true,
    ["AMD Radeon(TM) RX 9060 XT 16GB"] = true,
    ["AMD Radeon(TM) RX 9060 XT 8GB"] = true,
    ["AMD Radeon(TM) RX 9060 XTX"] = true,
    ["AMD Radeon(TM) RX 9060M"] = true,
    ["AMD Radeon(TM) RX 9070"] = true,
    ["AMD Radeon(TM) RX 9070 GRE"] = true,
    ["AMD Radeon(TM) RX 9070 XT"] = true,
    ["AMD Radeon(TM) RX 9070 XT 16GB"] = true,
    ["AMD Radeon(TM) RX 9070 XT 8GB"] = true,
    ["AMD Radeon(TM) RX 9070 XTX"] = true,
    ["AMD Radeon(TM) RX 9070M"] = true,
    ["Radeon RX 9060"] = true,
    ["Radeon RX 9060 GRE"] = true,
    ["Radeon RX 9060 XT"] = true,
    ["Radeon RX 9060 XT 16GB"] = true,
    ["Radeon RX 9060 XT 8GB"] = true,
    ["Radeon RX 9060 XTX"] = true,
    ["Radeon RX 9060M"] = true,
    ["Radeon RX 9070"] = true,
    ["Radeon RX 9070 GRE"] = true,
    ["Radeon RX 9070 XT"] = true,
    ["Radeon RX 9070 XT 16GB"] = true,
    ["Radeon RX 9070 XT 8GB"] = true,
    ["Radeon RX 9070 XTX"] = true,
    ["Radeon RX 9070M"] = true,
}

local amd_int8_names = {
    ["AMD Radeon 740M"] = true,
    ["AMD Radeon 740M Graphics"] = true,
    ["AMD Radeon 760M"] = true,
    ["AMD Radeon 760M Graphics"] = true,
    ["AMD Radeon 780M"] = true,
    ["AMD Radeon 780M Graphics"] = true,
    ["AMD Radeon 8040S"] = true,
    ["AMD Radeon 8040S Graphics"] = true,
    ["AMD Radeon 8050S"] = true,
    ["AMD Radeon 8050S Graphics"] = true,
    ["AMD Radeon 8060S"] = true,
    ["AMD Radeon 8060S Graphics"] = true,
    ["AMD Radeon 840M"] = true,
    ["AMD Radeon 840M Graphics"] = true,
    ["AMD Radeon 860M"] = true,
    ["AMD Radeon 860M Graphics"] = true,
    ["AMD Radeon 880M"] = true,
    ["AMD Radeon 880M Graphics"] = true,
    ["AMD Radeon 890M"] = true,
    ["AMD Radeon 890M Graphics"] = true,
    ["AMD Radeon RX 7600"] = true,
    ["AMD Radeon RX 7600 GRE"] = true,
    ["AMD Radeon RX 7600 XT"] = true,
    ["AMD Radeon RX 7600 XTX"] = true,
    ["AMD Radeon RX 7600M"] = true,
    ["AMD Radeon RX 7600M XT"] = true,
    ["AMD Radeon RX 7600S"] = true,
    ["AMD Radeon RX 7650"] = true,
    ["AMD Radeon RX 7650 GRE"] = true,
    ["AMD Radeon RX 7650 XT"] = true,
    ["AMD Radeon RX 7650 XTX"] = true,
    ["AMD Radeon RX 7650M"] = true,
    ["AMD Radeon RX 7650M XT"] = true,
    ["AMD Radeon RX 7650S"] = true,
    ["AMD Radeon RX 7700"] = true,
    ["AMD Radeon RX 7700 GRE"] = true,
    ["AMD Radeon RX 7700 XT"] = true,
    ["AMD Radeon RX 7700 XTX"] = true,
    ["AMD Radeon RX 7700M"] = true,
    ["AMD Radeon RX 7700M XT"] = true,
    ["AMD Radeon RX 7700S"] = true,
    ["AMD Radeon RX 7800"] = true,
    ["AMD Radeon RX 7800 GRE"] = true,
    ["AMD Radeon RX 7800 XT"] = true,
    ["AMD Radeon RX 7800 XTX"] = true,
    ["AMD Radeon RX 7800M"] = true,
    ["AMD Radeon RX 7800M XT"] = true,
    ["AMD Radeon RX 7800S"] = true,
    ["AMD Radeon RX 7900"] = true,
    ["AMD Radeon RX 7900 GRE"] = true,
    ["AMD Radeon RX 7900 XT"] = true,
    ["AMD Radeon RX 7900 XTX"] = true,
    ["AMD Radeon RX 7900M"] = true,
    ["AMD Radeon RX 7900M XT"] = true,
    ["AMD Radeon RX 7900S"] = true,
    ["AMD Radeon(TM) 740M"] = true,
    ["AMD Radeon(TM) 740M Graphics"] = true,
    ["AMD Radeon(TM) 760M"] = true,
    ["AMD Radeon(TM) 760M Graphics"] = true,
    ["AMD Radeon(TM) 780M"] = true,
    ["AMD Radeon(TM) 780M Graphics"] = true,
    ["AMD Radeon(TM) 8040S"] = true,
    ["AMD Radeon(TM) 8040S Graphics"] = true,
    ["AMD Radeon(TM) 8050S"] = true,
    ["AMD Radeon(TM) 8050S Graphics"] = true,
    ["AMD Radeon(TM) 8060S"] = true,
    ["AMD Radeon(TM) 8060S Graphics"] = true,
    ["AMD Radeon(TM) 840M"] = true,
    ["AMD Radeon(TM) 840M Graphics"] = true,
    ["AMD Radeon(TM) 860M"] = true,
    ["AMD Radeon(TM) 860M Graphics"] = true,
    ["AMD Radeon(TM) 880M"] = true,
    ["AMD Radeon(TM) 880M Graphics"] = true,
    ["AMD Radeon(TM) 890M"] = true,
    ["AMD Radeon(TM) 890M Graphics"] = true,
    ["AMD Radeon(TM) RX 7600"] = true,
    ["AMD Radeon(TM) RX 7600 GRE"] = true,
    ["AMD Radeon(TM) RX 7600 XT"] = true,
    ["AMD Radeon(TM) RX 7600 XTX"] = true,
    ["AMD Radeon(TM) RX 7600M"] = true,
    ["AMD Radeon(TM) RX 7600M XT"] = true,
    ["AMD Radeon(TM) RX 7600S"] = true,
    ["AMD Radeon(TM) RX 7650"] = true,
    ["AMD Radeon(TM) RX 7650 GRE"] = true,
    ["AMD Radeon(TM) RX 7650 XT"] = true,
    ["AMD Radeon(TM) RX 7650 XTX"] = true,
    ["AMD Radeon(TM) RX 7650M"] = true,
    ["AMD Radeon(TM) RX 7650M XT"] = true,
    ["AMD Radeon(TM) RX 7650S"] = true,
    ["AMD Radeon(TM) RX 7700"] = true,
    ["AMD Radeon(TM) RX 7700 GRE"] = true,
    ["AMD Radeon(TM) RX 7700 XT"] = true,
    ["AMD Radeon(TM) RX 7700 XTX"] = true,
    ["AMD Radeon(TM) RX 7700M"] = true,
    ["AMD Radeon(TM) RX 7700M XT"] = true,
    ["AMD Radeon(TM) RX 7700S"] = true,
    ["AMD Radeon(TM) RX 7800"] = true,
    ["AMD Radeon(TM) RX 7800 GRE"] = true,
    ["AMD Radeon(TM) RX 7800 XT"] = true,
    ["AMD Radeon(TM) RX 7800 XTX"] = true,
    ["AMD Radeon(TM) RX 7800M"] = true,
    ["AMD Radeon(TM) RX 7800M XT"] = true,
    ["AMD Radeon(TM) RX 7800S"] = true,
    ["AMD Radeon(TM) RX 7900"] = true,
    ["AMD Radeon(TM) RX 7900 GRE"] = true,
    ["AMD Radeon(TM) RX 7900 XT"] = true,
    ["AMD Radeon(TM) RX 7900 XTX"] = true,
    ["AMD Radeon(TM) RX 7900M"] = true,
    ["AMD Radeon(TM) RX 7900M XT"] = true,
    ["AMD Radeon(TM) RX 7900S"] = true,
    ["Radeon RX 7600"] = true,
    ["Radeon RX 7600 GRE"] = true,
    ["Radeon RX 7600 XT"] = true,
    ["Radeon RX 7600 XTX"] = true,
    ["Radeon RX 7600M"] = true,
    ["Radeon RX 7600M XT"] = true,
    ["Radeon RX 7600S"] = true,
    ["Radeon RX 7650"] = true,
    ["Radeon RX 7650 GRE"] = true,
    ["Radeon RX 7650 XT"] = true,
    ["Radeon RX 7650 XTX"] = true,
    ["Radeon RX 7650M"] = true,
    ["Radeon RX 7650M XT"] = true,
    ["Radeon RX 7650S"] = true,
    ["Radeon RX 7700"] = true,
    ["Radeon RX 7700 GRE"] = true,
    ["Radeon RX 7700 XT"] = true,
    ["Radeon RX 7700 XTX"] = true,
    ["Radeon RX 7700M"] = true,
    ["Radeon RX 7700M XT"] = true,
    ["Radeon RX 7700S"] = true,
    ["Radeon RX 7800"] = true,
    ["Radeon RX 7800 GRE"] = true,
    ["Radeon RX 7800 XT"] = true,
    ["Radeon RX 7800 XTX"] = true,
    ["Radeon RX 7800M"] = true,
    ["Radeon RX 7800M XT"] = true,
    ["Radeon RX 7800S"] = true,
    ["Radeon RX 7900"] = true,
    ["Radeon RX 7900 GRE"] = true,
    ["Radeon RX 7900 XT"] = true,
    ["Radeon RX 7900 XTX"] = true,
    ["Radeon RX 7900M"] = true,
    ["Radeon RX 7900M XT"] = true,
    ["Radeon RX 7900S"] = true,
}

local nvidia_int8_names = {
    ["NVIDIA GeForce RTX 2050"] = true,
    ["NVIDIA GeForce RTX 2050 D"] = true,
    ["NVIDIA GeForce RTX 2050 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2050 SUPER"] = true,
    ["NVIDIA GeForce RTX 2050 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2050 Ti"] = true,
    ["NVIDIA GeForce RTX 2050 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2050 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 2050 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2050D"] = true,
    ["NVIDIA GeForce RTX 2060"] = true,
    ["NVIDIA GeForce RTX 2060 D"] = true,
    ["NVIDIA GeForce RTX 2060 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2060 SUPER"] = true,
    ["NVIDIA GeForce RTX 2060 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2060 Ti"] = true,
    ["NVIDIA GeForce RTX 2060 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2060 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 2060 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2060D"] = true,
    ["NVIDIA GeForce RTX 2070"] = true,
    ["NVIDIA GeForce RTX 2070 D"] = true,
    ["NVIDIA GeForce RTX 2070 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2070 SUPER"] = true,
    ["NVIDIA GeForce RTX 2070 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2070 Ti"] = true,
    ["NVIDIA GeForce RTX 2070 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2070 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 2070 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2070D"] = true,
    ["NVIDIA GeForce RTX 2080"] = true,
    ["NVIDIA GeForce RTX 2080 D"] = true,
    ["NVIDIA GeForce RTX 2080 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2080 SUPER"] = true,
    ["NVIDIA GeForce RTX 2080 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2080 Ti"] = true,
    ["NVIDIA GeForce RTX 2080 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2080 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 2080 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 2080D"] = true,
    ["NVIDIA GeForce RTX 3050"] = true,
    ["NVIDIA GeForce RTX 3050 D"] = true,
    ["NVIDIA GeForce RTX 3050 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3050 SUPER"] = true,
    ["NVIDIA GeForce RTX 3050 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3050 Ti"] = true,
    ["NVIDIA GeForce RTX 3050 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3050 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 3050 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3050D"] = true,
    ["NVIDIA GeForce RTX 3060"] = true,
    ["NVIDIA GeForce RTX 3060 D"] = true,
    ["NVIDIA GeForce RTX 3060 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3060 SUPER"] = true,
    ["NVIDIA GeForce RTX 3060 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3060 Ti"] = true,
    ["NVIDIA GeForce RTX 3060 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3060 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 3060 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3060D"] = true,
    ["NVIDIA GeForce RTX 3070"] = true,
    ["NVIDIA GeForce RTX 3070 D"] = true,
    ["NVIDIA GeForce RTX 3070 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3070 SUPER"] = true,
    ["NVIDIA GeForce RTX 3070 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3070 Ti"] = true,
    ["NVIDIA GeForce RTX 3070 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3070 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 3070 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3070D"] = true,
    ["NVIDIA GeForce RTX 3080"] = true,
    ["NVIDIA GeForce RTX 3080 D"] = true,
    ["NVIDIA GeForce RTX 3080 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3080 SUPER"] = true,
    ["NVIDIA GeForce RTX 3080 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3080 Ti"] = true,
    ["NVIDIA GeForce RTX 3080 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3080 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 3080 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3080D"] = true,
    ["NVIDIA GeForce RTX 3090"] = true,
    ["NVIDIA GeForce RTX 3090 D"] = true,
    ["NVIDIA GeForce RTX 3090 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3090 SUPER"] = true,
    ["NVIDIA GeForce RTX 3090 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3090 Ti"] = true,
    ["NVIDIA GeForce RTX 3090 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3090 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 3090 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 3090D"] = true,
    ["NVIDIA GeForce RTX 4050"] = true,
    ["NVIDIA GeForce RTX 4050 D"] = true,
    ["NVIDIA GeForce RTX 4050 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4050 SUPER"] = true,
    ["NVIDIA GeForce RTX 4050 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4050 Ti"] = true,
    ["NVIDIA GeForce RTX 4050 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4050 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 4050 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4050D"] = true,
    ["NVIDIA GeForce RTX 4060"] = true,
    ["NVIDIA GeForce RTX 4060 D"] = true,
    ["NVIDIA GeForce RTX 4060 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4060 SUPER"] = true,
    ["NVIDIA GeForce RTX 4060 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4060 Ti"] = true,
    ["NVIDIA GeForce RTX 4060 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4060 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 4060 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4060D"] = true,
    ["NVIDIA GeForce RTX 4070"] = true,
    ["NVIDIA GeForce RTX 4070 D"] = true,
    ["NVIDIA GeForce RTX 4070 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4070 SUPER"] = true,
    ["NVIDIA GeForce RTX 4070 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4070 Ti"] = true,
    ["NVIDIA GeForce RTX 4070 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4070 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 4070 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4070D"] = true,
    ["NVIDIA GeForce RTX 4080"] = true,
    ["NVIDIA GeForce RTX 4080 D"] = true,
    ["NVIDIA GeForce RTX 4080 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4080 SUPER"] = true,
    ["NVIDIA GeForce RTX 4080 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4080 Ti"] = true,
    ["NVIDIA GeForce RTX 4080 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4080 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 4080 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4080D"] = true,
    ["NVIDIA GeForce RTX 4090"] = true,
    ["NVIDIA GeForce RTX 4090 D"] = true,
    ["NVIDIA GeForce RTX 4090 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4090 SUPER"] = true,
    ["NVIDIA GeForce RTX 4090 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4090 Ti"] = true,
    ["NVIDIA GeForce RTX 4090 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4090 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 4090 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 4090D"] = true,
    ["NVIDIA GeForce RTX 5050"] = true,
    ["NVIDIA GeForce RTX 5050 D"] = true,
    ["NVIDIA GeForce RTX 5050 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5050 SUPER"] = true,
    ["NVIDIA GeForce RTX 5050 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5050 Ti"] = true,
    ["NVIDIA GeForce RTX 5050 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5050 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 5050 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5050D"] = true,
    ["NVIDIA GeForce RTX 5060"] = true,
    ["NVIDIA GeForce RTX 5060 D"] = true,
    ["NVIDIA GeForce RTX 5060 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5060 SUPER"] = true,
    ["NVIDIA GeForce RTX 5060 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5060 Ti"] = true,
    ["NVIDIA GeForce RTX 5060 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5060 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 5060 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5060D"] = true,
    ["NVIDIA GeForce RTX 5070"] = true,
    ["NVIDIA GeForce RTX 5070 D"] = true,
    ["NVIDIA GeForce RTX 5070 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5070 SUPER"] = true,
    ["NVIDIA GeForce RTX 5070 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5070 Ti"] = true,
    ["NVIDIA GeForce RTX 5070 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5070 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 5070 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5070D"] = true,
    ["NVIDIA GeForce RTX 5080"] = true,
    ["NVIDIA GeForce RTX 5080 D"] = true,
    ["NVIDIA GeForce RTX 5080 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5080 SUPER"] = true,
    ["NVIDIA GeForce RTX 5080 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5080 Ti"] = true,
    ["NVIDIA GeForce RTX 5080 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5080 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 5080 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5080D"] = true,
    ["NVIDIA GeForce RTX 5090"] = true,
    ["NVIDIA GeForce RTX 5090 D"] = true,
    ["NVIDIA GeForce RTX 5090 Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5090 SUPER"] = true,
    ["NVIDIA GeForce RTX 5090 SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5090 Ti"] = true,
    ["NVIDIA GeForce RTX 5090 Ti Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5090 Ti SUPER"] = true,
    ["NVIDIA GeForce RTX 5090 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA GeForce RTX 5090D"] = true,
    ["NVIDIA RTX 2050"] = true,
    ["NVIDIA RTX 2050 D"] = true,
    ["NVIDIA RTX 2050 Laptop GPU"] = true,
    ["NVIDIA RTX 2050 SUPER"] = true,
    ["NVIDIA RTX 2050 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 2050 Ti"] = true,
    ["NVIDIA RTX 2050 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 2050 Ti SUPER"] = true,
    ["NVIDIA RTX 2050 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 2050D"] = true,
    ["NVIDIA RTX 2060"] = true,
    ["NVIDIA RTX 2060 D"] = true,
    ["NVIDIA RTX 2060 Laptop GPU"] = true,
    ["NVIDIA RTX 2060 SUPER"] = true,
    ["NVIDIA RTX 2060 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 2060 Ti"] = true,
    ["NVIDIA RTX 2060 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 2060 Ti SUPER"] = true,
    ["NVIDIA RTX 2060 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 2060D"] = true,
    ["NVIDIA RTX 2070"] = true,
    ["NVIDIA RTX 2070 D"] = true,
    ["NVIDIA RTX 2070 Laptop GPU"] = true,
    ["NVIDIA RTX 2070 SUPER"] = true,
    ["NVIDIA RTX 2070 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 2070 Ti"] = true,
    ["NVIDIA RTX 2070 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 2070 Ti SUPER"] = true,
    ["NVIDIA RTX 2070 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 2070D"] = true,
    ["NVIDIA RTX 2080"] = true,
    ["NVIDIA RTX 2080 D"] = true,
    ["NVIDIA RTX 2080 Laptop GPU"] = true,
    ["NVIDIA RTX 2080 SUPER"] = true,
    ["NVIDIA RTX 2080 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 2080 Ti"] = true,
    ["NVIDIA RTX 2080 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 2080 Ti SUPER"] = true,
    ["NVIDIA RTX 2080 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 2080D"] = true,
    ["NVIDIA RTX 3050"] = true,
    ["NVIDIA RTX 3050 D"] = true,
    ["NVIDIA RTX 3050 Laptop GPU"] = true,
    ["NVIDIA RTX 3050 SUPER"] = true,
    ["NVIDIA RTX 3050 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 3050 Ti"] = true,
    ["NVIDIA RTX 3050 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 3050 Ti SUPER"] = true,
    ["NVIDIA RTX 3050 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 3050D"] = true,
    ["NVIDIA RTX 3060"] = true,
    ["NVIDIA RTX 3060 D"] = true,
    ["NVIDIA RTX 3060 Laptop GPU"] = true,
    ["NVIDIA RTX 3060 SUPER"] = true,
    ["NVIDIA RTX 3060 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 3060 Ti"] = true,
    ["NVIDIA RTX 3060 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 3060 Ti SUPER"] = true,
    ["NVIDIA RTX 3060 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 3060D"] = true,
    ["NVIDIA RTX 3070"] = true,
    ["NVIDIA RTX 3070 D"] = true,
    ["NVIDIA RTX 3070 Laptop GPU"] = true,
    ["NVIDIA RTX 3070 SUPER"] = true,
    ["NVIDIA RTX 3070 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 3070 Ti"] = true,
    ["NVIDIA RTX 3070 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 3070 Ti SUPER"] = true,
    ["NVIDIA RTX 3070 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 3070D"] = true,
    ["NVIDIA RTX 3080"] = true,
    ["NVIDIA RTX 3080 D"] = true,
    ["NVIDIA RTX 3080 Laptop GPU"] = true,
    ["NVIDIA RTX 3080 SUPER"] = true,
    ["NVIDIA RTX 3080 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 3080 Ti"] = true,
    ["NVIDIA RTX 3080 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 3080 Ti SUPER"] = true,
    ["NVIDIA RTX 3080 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 3080D"] = true,
    ["NVIDIA RTX 3090"] = true,
    ["NVIDIA RTX 3090 D"] = true,
    ["NVIDIA RTX 3090 Laptop GPU"] = true,
    ["NVIDIA RTX 3090 SUPER"] = true,
    ["NVIDIA RTX 3090 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 3090 Ti"] = true,
    ["NVIDIA RTX 3090 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 3090 Ti SUPER"] = true,
    ["NVIDIA RTX 3090 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 3090D"] = true,
    ["NVIDIA RTX 4050"] = true,
    ["NVIDIA RTX 4050 D"] = true,
    ["NVIDIA RTX 4050 Laptop GPU"] = true,
    ["NVIDIA RTX 4050 SUPER"] = true,
    ["NVIDIA RTX 4050 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 4050 Ti"] = true,
    ["NVIDIA RTX 4050 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 4050 Ti SUPER"] = true,
    ["NVIDIA RTX 4050 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 4050D"] = true,
    ["NVIDIA RTX 4060"] = true,
    ["NVIDIA RTX 4060 D"] = true,
    ["NVIDIA RTX 4060 Laptop GPU"] = true,
    ["NVIDIA RTX 4060 SUPER"] = true,
    ["NVIDIA RTX 4060 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 4060 Ti"] = true,
    ["NVIDIA RTX 4060 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 4060 Ti SUPER"] = true,
    ["NVIDIA RTX 4060 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 4060D"] = true,
    ["NVIDIA RTX 4070"] = true,
    ["NVIDIA RTX 4070 D"] = true,
    ["NVIDIA RTX 4070 Laptop GPU"] = true,
    ["NVIDIA RTX 4070 SUPER"] = true,
    ["NVIDIA RTX 4070 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 4070 Ti"] = true,
    ["NVIDIA RTX 4070 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 4070 Ti SUPER"] = true,
    ["NVIDIA RTX 4070 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 4070D"] = true,
    ["NVIDIA RTX 4080"] = true,
    ["NVIDIA RTX 4080 D"] = true,
    ["NVIDIA RTX 4080 Laptop GPU"] = true,
    ["NVIDIA RTX 4080 SUPER"] = true,
    ["NVIDIA RTX 4080 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 4080 Ti"] = true,
    ["NVIDIA RTX 4080 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 4080 Ti SUPER"] = true,
    ["NVIDIA RTX 4080 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 4080D"] = true,
    ["NVIDIA RTX 4090"] = true,
    ["NVIDIA RTX 4090 D"] = true,
    ["NVIDIA RTX 4090 Laptop GPU"] = true,
    ["NVIDIA RTX 4090 SUPER"] = true,
    ["NVIDIA RTX 4090 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 4090 Ti"] = true,
    ["NVIDIA RTX 4090 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 4090 Ti SUPER"] = true,
    ["NVIDIA RTX 4090 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 4090D"] = true,
    ["NVIDIA RTX 5050"] = true,
    ["NVIDIA RTX 5050 D"] = true,
    ["NVIDIA RTX 5050 Laptop GPU"] = true,
    ["NVIDIA RTX 5050 SUPER"] = true,
    ["NVIDIA RTX 5050 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 5050 Ti"] = true,
    ["NVIDIA RTX 5050 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 5050 Ti SUPER"] = true,
    ["NVIDIA RTX 5050 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 5050D"] = true,
    ["NVIDIA RTX 5060"] = true,
    ["NVIDIA RTX 5060 D"] = true,
    ["NVIDIA RTX 5060 Laptop GPU"] = true,
    ["NVIDIA RTX 5060 SUPER"] = true,
    ["NVIDIA RTX 5060 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 5060 Ti"] = true,
    ["NVIDIA RTX 5060 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 5060 Ti SUPER"] = true,
    ["NVIDIA RTX 5060 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 5060D"] = true,
    ["NVIDIA RTX 5070"] = true,
    ["NVIDIA RTX 5070 D"] = true,
    ["NVIDIA RTX 5070 Laptop GPU"] = true,
    ["NVIDIA RTX 5070 SUPER"] = true,
    ["NVIDIA RTX 5070 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 5070 Ti"] = true,
    ["NVIDIA RTX 5070 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 5070 Ti SUPER"] = true,
    ["NVIDIA RTX 5070 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 5070D"] = true,
    ["NVIDIA RTX 5080"] = true,
    ["NVIDIA RTX 5080 D"] = true,
    ["NVIDIA RTX 5080 Laptop GPU"] = true,
    ["NVIDIA RTX 5080 SUPER"] = true,
    ["NVIDIA RTX 5080 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 5080 Ti"] = true,
    ["NVIDIA RTX 5080 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 5080 Ti SUPER"] = true,
    ["NVIDIA RTX 5080 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 5080D"] = true,
    ["NVIDIA RTX 5090"] = true,
    ["NVIDIA RTX 5090 D"] = true,
    ["NVIDIA RTX 5090 Laptop GPU"] = true,
    ["NVIDIA RTX 5090 SUPER"] = true,
    ["NVIDIA RTX 5090 SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 5090 Ti"] = true,
    ["NVIDIA RTX 5090 Ti Laptop GPU"] = true,
    ["NVIDIA RTX 5090 Ti SUPER"] = true,
    ["NVIDIA RTX 5090 Ti SUPER Laptop GPU"] = true,
    ["NVIDIA RTX 5090D"] = true,
}

local intel_int8_names = {
    ["Intel Arc 130T"] = true,
    ["Intel Arc 130T GPU"] = true,
    ["Intel Arc 130T GPU (16GB)"] = true,
    ["Intel Arc 130T GPU (8GB)"] = true,
    ["Intel Arc 130T Graphics"] = true,
    ["Intel Arc 130V"] = true,
    ["Intel Arc 130V GPU"] = true,
    ["Intel Arc 130V GPU (16GB)"] = true,
    ["Intel Arc 130V GPU (8GB)"] = true,
    ["Intel Arc 130V Graphics"] = true,
    ["Intel Arc 140T"] = true,
    ["Intel Arc 140T GPU"] = true,
    ["Intel Arc 140T GPU (16GB)"] = true,
    ["Intel Arc 140T GPU (8GB)"] = true,
    ["Intel Arc 140T Graphics"] = true,
    ["Intel Arc 140V"] = true,
    ["Intel Arc 140V GPU"] = true,
    ["Intel Arc 140V GPU (16GB)"] = true,
    ["Intel Arc 140V GPU (8GB)"] = true,
    ["Intel Arc 140V Graphics"] = true,
    ["Intel Arc A310"] = true,
    ["Intel Arc A310 Graphics"] = true,
    ["Intel Arc A380"] = true,
    ["Intel Arc A380 Graphics"] = true,
    ["Intel Arc A580"] = true,
    ["Intel Arc A580 Graphics"] = true,
    ["Intel Arc A750"] = true,
    ["Intel Arc A750 Graphics"] = true,
    ["Intel Arc A770"] = true,
    ["Intel Arc A770 Graphics"] = true,
    ["Intel Arc B570"] = true,
    ["Intel Arc B570 Graphics"] = true,
    ["Intel Arc B580"] = true,
    ["Intel Arc B580 Graphics"] = true,
    ["Intel Arc Graphics"] = true,
    ["Intel(R) Arc(TM) 130T"] = true,
    ["Intel(R) Arc(TM) 130T GPU"] = true,
    ["Intel(R) Arc(TM) 130T GPU (16GB)"] = true,
    ["Intel(R) Arc(TM) 130T GPU (8GB)"] = true,
    ["Intel(R) Arc(TM) 130T Graphics"] = true,
    ["Intel(R) Arc(TM) 130V"] = true,
    ["Intel(R) Arc(TM) 130V GPU"] = true,
    ["Intel(R) Arc(TM) 130V GPU (16GB)"] = true,
    ["Intel(R) Arc(TM) 130V GPU (8GB)"] = true,
    ["Intel(R) Arc(TM) 130V Graphics"] = true,
    ["Intel(R) Arc(TM) 140T"] = true,
    ["Intel(R) Arc(TM) 140T GPU"] = true,
    ["Intel(R) Arc(TM) 140T GPU (16GB)"] = true,
    ["Intel(R) Arc(TM) 140T GPU (8GB)"] = true,
    ["Intel(R) Arc(TM) 140T Graphics"] = true,
    ["Intel(R) Arc(TM) 140V"] = true,
    ["Intel(R) Arc(TM) 140V GPU"] = true,
    ["Intel(R) Arc(TM) 140V GPU (16GB)"] = true,
    ["Intel(R) Arc(TM) 140V GPU (8GB)"] = true,
    ["Intel(R) Arc(TM) 140V Graphics"] = true,
    ["Intel(R) Arc(TM) A310"] = true,
    ["Intel(R) Arc(TM) A310 Graphics"] = true,
    ["Intel(R) Arc(TM) A380"] = true,
    ["Intel(R) Arc(TM) A380 Graphics"] = true,
    ["Intel(R) Arc(TM) A580"] = true,
    ["Intel(R) Arc(TM) A580 Graphics"] = true,
    ["Intel(R) Arc(TM) A750"] = true,
    ["Intel(R) Arc(TM) A750 Graphics"] = true,
    ["Intel(R) Arc(TM) A770"] = true,
    ["Intel(R) Arc(TM) A770 Graphics"] = true,
    ["Intel(R) Arc(TM) B570"] = true,
    ["Intel(R) Arc(TM) B570 Graphics"] = true,
    ["Intel(R) Arc(TM) B580"] = true,
    ["Intel(R) Arc(TM) B580 Graphics"] = true,
    ["Intel(R) Arc(TM) Graphics"] = true,
}

local function detect_fsr4_policy()
    if system == nil or system.get_gpu == nil then
        install.log("当前启动器未提供 system.get_gpu，FSR4 GPU 策略保持 auto")
        return
    end
    local gpu = system.get_gpu()
    if gpu == nil then
        install.log("system.get_gpu 未返回数据，FSR4 GPU 策略保持 auto")
        return
    end
    if gpu.name ~= nil then
        gpu_name = gpu.name
    end
    if gpu.vendor ~= nil then
        gpu_vendor = gpu.vendor
    end
    if gpu_vendor == "AMD" and amd_fp8_names[gpu_name] == true then
        fsr4_update = "true"
        fsr4_upscaler_index = "0"
        fsr4_force_int8 = "false"
        fsr4_mode = "fp8"
    elseif gpu_vendor == "NVIDIA" and nvidia_int8_names[gpu_name] == true then
        fsr4_update = "true"
        fsr4_upscaler_index = "0"
        fsr4_force_int8 = "true"
        fsr4_mode = "int8"
    elseif gpu_vendor == "AMD" and amd_int8_names[gpu_name] == true then
        fsr4_update = "true"
        fsr4_upscaler_index = "0"
        fsr4_force_int8 = "true"
        fsr4_mode = "int8"
    elseif gpu_vendor == "Intel" and intel_int8_names[gpu_name] == true then
        fsr4_update = "true"
        fsr4_upscaler_index = "0"
        fsr4_force_int8 = "true"
        fsr4_mode = "int8"
    else
        install.log("未识别的 GPU 型号，FSR4 策略保持 auto: " .. gpu_name .. " (" .. gpu_vendor .. ")")
    end
end

if pcall ~= nil then
    pcall(detect_fsr4_policy)
else
    detect_fsr4_policy()
end

install.log("显卡: " .. gpu_name .. " (" .. gpu_vendor .. ")，FSR4 模式: " .. fsr4_mode)

local plugin_id = "FSR-Bridge-Plugin"
local plugins_dir = install.get_plugins_dir()
local plugin_dir = plugins_dir .. "\\" .. plugin_id
local payload_dir = plugin_dir .. "\\payload"
local opti_root_dir = payload_dir .. "\\OptiScaler"
local opti_dir = opti_root_dir
local config_stage_dir = plugin_dir .. "\\._lua_config_stage"
install.log("插件目录: " .. plugin_dir)

install.set_progress(0, "正在准备原神 FSR2 桥接插件")

local result = install.download_plugin(plugin_id)
if result == nil or not result.success then
    local message = result and result.error or "官方插件服务未返回成功结果"
    install.log("下载错误: " .. message)
    install.show_notification("安装错误", message, "error", 5000)
    return
end

if install.file_exists(opti_root_dir .. "\\OptiScaler.dll") then
    opti_dir = opti_root_dir
else
    local message = "插件包缺少 OptiScaler.dll"
    install.log(message)
    install.show_notification("安装错误", message, "error", 5000)
    return
end
install.log("OptiScaler 运行目录: " .. opti_dir)

install.set_progress(82, "正在写入插件配置")
install.write_config(plugin_dir, {
    General = {
        Name = "原神FSR2桥接插件",
        Description = "支持把原神的FSR2转换为FSR4、DLSS、XESS",
        Developer = "シリアCelia",
        File = "FSR-Bridge-Plugin.dll",
        Version = "1.1.5"
    },
    EnableBridge = {
        Name = "启用 FSR Bridge",
        Type = "bool",
        Value = "1"
    },
    EnableOptiScaler = {
        Name = "启用 OptiScaler（需要 Bridge）",
        Type = "bool",
        Value = "1"
    },
    EnableReShade = {
        Name = "启用 ReShade",
        Type = "bool",
        Value = "1"
    },
    IssueFeedback = {
        Name = "问题反馈",
        Type = "string",
        Value = "https://github.com/AizawaHikaru233/genshin_fsr_brigde/issues"
    },
    CommunityGroup = {
        Name = "交流群",
        Type = "string",
        Value = "928147257"
    },
    ResetConfigurations = {
        Name = "重置所有配置文件（自行更换插件版本或出现问题时使用）",
        Type = "bool",
        Value = "1"
    }
})

install.set_progress(90, "正在准备官方默认配置")
install.delete(opti_dir .. "\\OptiScaler.ini")
install.create_dir(config_stage_dir)
install.write_config(config_stage_dir, {
    FSR4Policy = {
        UpscalerIndex = fsr4_upscaler_index,
        Fsr4Update = fsr4_update,
        Fsr4ForceEnableInt8 = fsr4_force_int8
    }
})
install.move_file(config_stage_dir .. "\\config.ini", plugin_dir .. "\\FSR4Policy.ini")
install.delete(config_stage_dir)

local bundled_dlss = payload_dir .. "\\NVIDIA\\DLSS\\nvngx_dlss.dll"
local bundled_dlss_license = payload_dir .. "\\NVIDIA\\DLSS\\nvngx_dlss.license.txt"
if install.file_exists(bundled_dlss) then
    install.copy_file(bundled_dlss, opti_dir .. "\\nvngx_dlss.dll")
    if install.file_exists(bundled_dlss_license) then
        install.copy_file(bundled_dlss_license, opti_dir .. "\\nvngx_dlss.license.txt")
    end
    install.log("已将 NVIDIA DLSS 组件复制到 OptiScaler 运行目录")
else
    install.log("插件包未包含 NVIDIA DLSS 组件，跳过复制")
end

install.set_progress(100, "安装完成")
install.show_notification("安装成功", "原神FSR2桥接插件已就绪", "success", 5000)
